repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.3
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer
